theme = "solar-theme-hugo"
baseURL = "https://someguyontheinter.net/"
languageCode = "en-us"
title = "some guy on the Internet"

pygmentsCodeFences = true
pygmentsStyle = "solarized-light"

disqusShortname = "someguyontheinternet"

enableRobotsTXT = true

[params]
  description = "the network engineer fears the backhoe, and the systems engineer fears the network engineer"

  # solar-theme-hugo
  scheme = "light"

[permalinks]
  blog = "/blog/:filename/"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "s3"
URL = "s3://someguyontheinter.net?region=us-east-1"  # For S3; see https://gocloud.dev/howto/blob/open-bucket/#s3.
# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E37J0D59XZB9ZC"


[[deployment.matchers]]
#  Cache static assets for 20 years.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = false
