theme = "solar-theme-hugo"
baseURL = "https://someguyontheinter.net/"
languageCode = "en-us"
title = "some guy on the Internet"

pygmentsCodeFences = true
pygmentsStyle = "solarized-light"

disqusShortname = "someguyontheinternet"

enableRobotsTXT = true

googleAnalytics = "UA-152038167-2"

[params]
  description = "the network engineer fears the backhoe, and the systems engineer fears the network engineer"

  # solar-theme-hugo
  scheme = "light"

[permalinks]
  blog = "/blog/:filename/"
