version: 2.1

orbs:
  docker: circleci/docker@0.5.13

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          lint-dockerfile: true
          treat-warnings-as-errors: true
          deploy: false
          image: $CIRCLE_PROJECT_USERNAME/someguyontheinternet
