version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.2.0

workflows:
  build-and-publish-docker-image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${ECR_REPO_PROD}"
          tag: "${CIRCLE_SHA1}"
